version: "3.8"
services:
  db: 
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres1234 #BYUIds2017
    volumes:   
      - ./data/postgresql:/var/lib/postgresql/data 
      - ./scratch:/scratch 
    ports:
      - '5432:5432'
    networks:
      - n451

  spark:
    image: jupyter/all-spark-notebook
    depends_on:
      - db
    ports:
      - '8888:8888'
      - '4040:4040' 
      - '4041:4041'
    volumes:
      - ./scripts:/home/jovyan/scripts
      - ./scratch:/home/jovyan/scratch
      - ./work:/home/jovyan/work
      - ./data:/home/jovyan/data
    networks:
      - n451

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - ./scratch:/scratch
    networks:
      - n451

networks:
  n451: